### ISSUE TITLE
关于模型

### ISSUE THREAD

**Issue by AIHHU** [JusperLee/AFRCNN-For-Speech-Separation#4]
请问AFRCNN和AFRCNN（sum）哪个训练的比较快呢？，我昨晚跑了AFRCNN（sum）用的v100(32G)服务器，一个晚上貌似只跑了2个epoch，学长是不是用了多卡训练？

**Comment by JusperLee** [comment]
sum会更快，但是效果会比较差一些，而且我都是8卡训练。你可以按照我新上传的https://github.com/JusperLee/AFRCNN-For-Speech-Separation/blob/master/AFRCNN.py这个代码进行修改。训练速度应该会得到提升。需要修改的地方如下：
https://github.com/JusperLee/AFRCNN-For-Speech-Separation/blob/8be8a33b87c7e294296c141c861f84736982a7c2/AFRCNN.py#L228

把torch.cat改成sum即可。

**Comment by JusperLee** [comment]
我已经修改了AFRCNN（sum）网络的代码，请查看。

**Comment by AIHHU** [comment]
学长，这两天我跑过了，宁这个效果巨好，刚看到消息，请问AFRCNN(sum)您后面改了什么呢？我跑的是之前那一版

**Comment by JusperLee** [comment]
没有改什么，就是把cat改成了sum

**Comment by AIHHU** [comment]
不是不是，就是宁两天前放上去的AFRCNN

**Comment by AIHHU** [comment]
就是前两天放上去的AFRCNN(sum)，那个我看了一下，好像改了空洞卷积，是吗？那个是跑起来更快了吗？

**Comment by JusperLee** [comment]
是的，但是之前也是一样，我只不过把代码重构了一下看起来规范一些。但是不知道为什么重构的代码存在问题。我就上传了之前的代码。

**Comment by AIHHU** [comment]
哈哈哈，这就很软工
